package io.github.binaryfoo.lagotto.gnuplot

object GnuplotScriptAuthor {

  def write(fields: Seq[String], xsvFileName: String): String = {
    val timefmt = fields.head match {
      case "time" => "%H:%M:%S"
      case "time(HH:mm:ss)" => "%H:%M:%S"
      case "time(HH:mm:s0)" => "%H:%M:%S"
      case "time(HH:mm)" => "%H:%M"
      case "time(HH:m0)" => "%H:%M"
    }

    val columns = fields.tail

    s"""set xdata time
      |set timefmt '$timefmt'
      |set format x '$timefmt'
      |set multiplot layout ${columns.size},1 title 'Auto-generated by lago'
      |set lmargin 5
      |set xrange [] writeback
      |do for [i=2:${fields.size}] {
      |    plot '$xsvFileName' using 1:i w lines t column(i)
      |    set xrange restore
      |}
      |""".stripMargin
  }
}
