package io.github.binaryfoo.lagotto.output

import io.github.binaryfoo.lagotto.MsgPairFieldAccess

import scala.annotation.tailrec

object GnuplotScriptWriter {

  val ToSecondPrecision = """time\(HH:[m0]{2}:[s0]{2}\)""".r
  val ToMinutePrecision = """time\(HH:[m0]{2}\)""".r
  val DateTimeToSecondPrecision = """time\(yyyy-MM-dd HH:[m0]{2}:[s0]{2}\)""".r
  val DateTimeToMinutePrecision = """time\(yyyy-MM-dd HH:[m0]{2}\)""".r

  def write(fields: Seq[String], csvFileName: String, plotFileName: String, xRange: (String, String), plotStyle: PlotStyle): String = {
    val timeFormat = toGnuplotTimeFormat(fields.head)
    val columns = fields.tail
    val (firstTime, lastTime) = xRange

    // using tab delimited data fails on empty cells: \t\t gets merged
    // line types cheat sheet: http://kunak.phsx.ku.edu/~sergei/Gnuplot/line_point_types.html

    val height = 960 * math.max(1, fields.size / 6)

    val header = s"""#!/usr/bin/env gnuplot
        |set datafile separator ','
        |set terminal svg enhanced mouse standalone size 1280,$height
        |set output '$plotFileName.svg'
        |#set terminal pngcairo size 1280,$height
        |#set output '$plotFileName.png'
        |set xdata time
        |set timefmt '$timeFormat'
        |set format x '$timeFormat'
        |set lmargin 10
        |set xrange ['$firstTime':'$lastTime']
        |set title 'Auto-generated by lago'
        |""".stripMargin

    val body = plotStyle match {
      case ChartPerColumn =>
        s"""|set multiplot layout ${columns.size},1
            |do for [i=2:${fields.size}] {
            |    plot '$csvFileName' using 1:i w lines lt 3 t column(i)
            |}
            |""".stripMargin
      case SingleChart =>
        s"""|plot for [i=2:${fields.size}] '$csvFileName' using 1:i w lines lt i t column(i)
            |""".stripMargin
      case ChartPerCluster(clusters) =>
        clusters.map { cluster =>
          s"""plot for [j in "${cluster.mkString(" ")}"] i=j+0 '$csvFileName' using 1:i w lines lt i t column(i)"""
        }.mkString(s"set multiplot layout ${clusters.size},1\n", "\n", "")
    }

    header + body
  }

  @tailrec
  private def toGnuplotTimeFormat(field: String): String = {
    field match {
      case "time" => "%H:%M:%S"
      case ToSecondPrecision() => "%H:%M:%S"
      case ToMinutePrecision() => "%H:%M"
      case "date" => "%Y-%m-%d"
      case "datetime" => "%Y-%m-%d %H:%M:%S"
      case DateTimeToSecondPrecision() => "%Y-%m-%d %H:%M:%S"
      case DateTimeToMinutePrecision() => "%Y-%m-%d %H:%M"
      case MsgPairFieldAccess(_, expr) => toGnuplotTimeFormat(expr)
    }
  }
}

sealed trait PlotStyle
object ChartPerColumn extends PlotStyle
object SingleChart extends PlotStyle
case class ChartPerCluster(clusters: Seq[Seq[Int]]) extends PlotStyle
