package io.github.binaryfoo.lagotto.output

object GnuplotScriptWriter {

  def write(fields: Seq[String], csvFileName: String, baseName: String, xRange: (String, String)): String = {
    val timeFormat = fields.head match {
      case "time" => "%H:%M:%S"
      case "time(HH:mm:ss)" => "%H:%M:%S"
      case "time(HH:mm:s0)" => "%H:%M:%S"
      case "time(HH:mm)" => "%H:%M"
      case "time(HH:m0)" => "%H:%M"
    }
    val columns = fields.tail
    val (firstTime, lastTime) = xRange

    // using tab delimited data fails on empty cells: \t\t gets merged
    // line types cheat sheet: http://kunak.phsx.ku.edu/~sergei/Gnuplot/line_point_types.html
    
    s"""#!/usr/bin/env gnuplot -persist
      |set datafile separator ','
      |#set terminal svg size 1280,960
      |#set output '$baseName.svg'
      |set xdata time
      |set timefmt '$timeFormat'
      |set format x '$timeFormat'
      |set multiplot layout ${columns.size},1 title 'Auto-generated by lago'
      |set lmargin 5
      |set xrange ['$firstTime':'$lastTime']
      |#set xrange [] writeback
      |do for [i=2:${fields.size}] {
      |    plot '$csvFileName' using 1:i w lines lt 3 t column(i)
      |    #set xrange restore
      |}
      |""".stripMargin
  }
}
